[package]
name = "dag-cbor-derive"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
async-trait = "0.1"
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
synstructure = "0.12.0"

[dev-dependencies]
async-std = "0.99"
cid = { git = "https://github.com/dvc94ch/rust-cid", branch = "cli" }
libipld = { path = ".." }
trybuild = "1.0"
