[package]
name = "rust-ipld"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
cid = { git = "https://github.com/multiformats/rust-cid", branch = "master" }
failure = "0.1"