[package]
name = "libipld"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
async-trait = "0.1"
byteorder = "*"
cid = { git = "https://github.com/dvc94ch/rust-cid", branch = "cli" }
failure = "0.1"
multibase = { git = "https://github.com/multiformats/rust-multibase" }
multihash = { git = "https://github.com/dvc94ch/rust-multihash", branch = "cli" }

[dev-dependencies]
async-std = "0.99"

[workspace]
members = [
  "cache",
  "dag-cbor-derive",
  "store",
]
