[package]
name = "libipld"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
byteorder = "*"
cid = { git = "https://github.com/dvc94ch/rust-cid", branch = "cli" }
failure = "0.1"
multibase = { git = "https://github.com/dvc94ch/rust-multibase", branch = "cli" }
multihash = { git = "https://github.com/dvc94ch/rust-multihash", branch = "cli" }

[workspace]
members = [
  "derive",
]
