[package]
name = "libipld-json"
version = "0.2.0"
authors = ["Irakli Gozalishvili <contact@gozala.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "ipld json codec"
repository = "https://github.com/ipfs-rust/rust-ipld"

[dependencies]
base64 = "0.12.1"
libipld-core = { version = "0.2.0", path = "../core" }
serde_json = "1.0.52"
serde = { version = "1.0.106", features = ["derive"] }
