[package]
name = "block-store"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
async-std = "0.99"
async-trait = "0.1"
libipld = { path = ".." }
multibase = { git = "https://github.com/multiformats/rust-multibase" }

[dev-dependencies]
tempdir = "0.3"
